apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: base

resources:
  - deployment.yml
  - service.yml

labels:
- includeTemplates: true
  includeSelectors: true
  pairs:
    app: vfmp
