apiVersion: v1
kind: Service
metadata:
  name: vfmp
spec:
  selector:
    app: vfmp
  ports:
    - protocol: TCP
      name: service-http
      port: 8080
      targetPort: 8080
    - protocol: TCP
      name: clients-tcp
      port: 9090
      targetPort: 9090
    - protocol: TCP
      name: metrics-http
      port: 5050
      targetPort: 5050
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 192.168.8.20
