on: 
  push:
    branches:
      - main
  pull_request:


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: golangci-lint
        uses: https://github.com/golangci/golangci-lint-action@v9
        with:
          version: v2.8

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Build
        run: go build main.go

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Run tests
        run: go run gotest.tools/gotestsum@latest --format=testname
