on: 
  push:
    branches:
      - main
  pull_request:


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: golangci-lint
        uses: https://github.com/golangci/golangci-lint-action@v9
        with:
          version: v2.8

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Build
        run: go build -o vfmp

  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Run unit tests
        run: go run gotest.tools/gotestsum@latest --format=testname ./internal/...

  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v6
        with:
          go-version: stable
      - name: Start service
        run: go run main.go -config "config.test.yml" -log-path vfmp.log &
      - name: Run integration tests
        run: go run gotest.tools/gotestsum@latest --format=testname ./tests/... -config-path "../config.test.yml"
      - uses: actions/upload-artifact@v6
        with:
          name: vfmp.log
          path: vfmp.log
