name: Build

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: choice
        options:
          - dev
          - prod

env:
  REGISTRY: git.molloy.xyz
  IMAGE_NAME: ${{ github.repository }}


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        name: Checkout repo
      - uses: https://data.forgejo.org/actions/setup-go@v6
        name: Setup go
        with:
          go-version-file: go.mod
      - name: Check formatting
        run: |
          unformatted="$(gofmt -l -e .)"
          if [ -n "$unformatted" ]; then
            echo "The following files have not been formatted:"
            echo "$unformatted"
            exit 1
          fi
      - name: Check lints
        uses: https://github.com/golangci/golangci-lint-action@v9
        with:
          version: v2.8

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        name: Checkout repo
      - uses: https://data.forgejo.org/actions/setup-go@v6
        name: Setup go
        with:
          go-version-file: go.mod
      - name: Build
        run: go build -o vfmp ./cmd/vfmp/main.go

  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        name: Checkout repo
      - uses: https://data.forgejo.org/actions/setup-go@v6
        name: Setup go
        with:
          go-version-file: go.mod
      - name: Run unit tests
        run: go run gotest.tools/gotestsum@latest --format=testname ./internal/...

  integration:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        name: Checkout repo
      - uses: https://data.forgejo.org/actions/setup-go@v6
        name: Setup go
        with:
          go-version-file: go.mod
      - name: Run integration tests
        run: |
          go build -o vfmp ./cmd/vfmp/main.go
          ./vfmp -config "config.test.yml" > vfmp.log 2>&1 &
          sleep 1
          go run gotest.tools/gotestsum@latest --format=testname ./tests/... -config "../config.test.yml"
      - uses: actions/upload-artifact@v3
        name: Upload logs
        if: failure()
        with:
          name: vfmp.log
          path: vfmp.log

  build-and-push-image:
    name: Build Docker Image
    if: ${{ github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    needs:
      - lint
      - build
      - unit
      - integration
    steps:
      - uses: actions/checkout@v6
        name: Checkout repo
        with:
          fetch-depth: 0
      - uses: docker/login-action@v3
        name: Login to registry
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Calculate version
        id: version
        run: |
          VERSION="$(git describe --match='v[0-9].[0-9].[0-9]' --tags "$FORGEJO_REF" || true)"
          echo "$VERSION"
          echo "version=$VERSION" >> $FORGEJO_OUTPUT

      - uses: docker/metadata-action@v4
        name: Generate image metadata
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=raw,value=${{ steps.version.outputs.version }},enable=${{ !startsWith(github.ref_name, 'v') }}

      - uses: docker/setup-buildx-action@v3
        name: Setup buildx

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: deploy/Dockerfile
          build-args: "VERSION=${{ steps.version.outputs.version }}"
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-dev:
    name: Deploy Dev
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && inputs.environment == 'dev')
    needs: [build-and-push-image]
    steps:
      - uses: actions/checkout@v6
        name: Checkout repo
      - name: Tag Commit
        run: |
          echo "tagging ${{ github.sha }} as dev"
          git tag -f dev ${{ github.sha }}
          git push origin dev --force

      - name: Install kubectl
        uses: https://github.com/Azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Setup kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          sed -i 's/placeholder-version/${{needs.build-and-push-image.outputs.version}}/' deploy/k8s/overlays/dev/kustomization.yml
          echo "================"
          echo "| Service Spec |"
          echo "================"
          kubectl kustomize deploy/k8s/overlays/dev
          echo "================"
          echo "| Deploying... |"
          echo "================"
          kubectl apply -k deploy/k8s/overlays/dev
          kubectl rollout status deployment/vfmp -n dev --timeout=5m

  deploy-prod:
    name: Deploy Prod
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && inputs.environment == 'prod'
    needs: [build-and-push-image]
    steps:
      - uses: actions/checkout@v6
        name: Checkout repo
        with:
          fetch-depth: 0

      - name: Check semver tag
        run: |
          if ! git tag --points-at HEAD | grep -qE '^v[0-9]+\.[0-9]+\.[0-9]+$'; then
            echo "Error: current commit must be tagged with a semver version (e.g. v1.2.3)"
            exit 1
          fi

      - name: Tag Commit
        run: |
          echo "tagging ${{ github.sha }} as prod"
          git tag -f prod ${{ github.sha }}
          git push origin prod --force

      - name: Install kubectl
        uses: https://github.com/Azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Setup kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          sed 's/placeholder-version/${{needs.build-and-push-image.outputs.version}}/' deploy/k8s/overlays/prod/kustomization.yml && cat deploy/k8s/overlays/prod/kustomization.yml
          kubectl apply -k deploy/k8s/overlays/prod
          kubectl rollout status deployment/vfmp -n prod --timeout=5m
