apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: dev

images:
- name: vfmp
  newName: git.molloy.xyz/fergus-molloy/vfmp
  newTag: placeholder-version

labels:
- includeTemplates: true
  pairs:
    environment: dev
    version: placeholder-version
