apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: dev

images:
- name: vfmp
  newName: git.molloy.xyz/fergus-molloy/vfmp
  newTag: v1.1.2-25-g757bbb6

labels:
- includeTemplates: true
  pairs:
    environment: dev
    version: v1.1.2-25-g757bbb6
